services:
    enterprise-opa:
        image: ghcr.io/styrainc/enterprise-opa:latest
        ports:
            - "8181:8181"
        command:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--log-level=debug"
        environment:
            EOPA_LICENSE_KEY: ${EOPA_LICENSE_KEY}
            HTTP_PROXY: proxy:3128
            HTTPS_PROXY: proxy:3128
        networks:
            intnet: {}
        depends_on:
            - proxy
            - dns
        volumes:
            - ./resolv.conf:/etc/resolv.conf

    dns:
        image: coredns/coredns
        ports:
            - "53:53"
        networks:
            intnet: {}
            extnet: {}

    proxy:
        image: hinata/nginx-forward-proxy:latest
        ports:
            - "3128:3128"
        networks:
            intnet: {}
            extnet: {}

networks:
    intnet:
        internal: true
    extnet: {}
