version: "3.9"

services:
  s3:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    expose:
    - "9000"
    - "9001"
    ports:
    - "9000:9000"
    - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  bucket:
    image: quay.io/minio/mc:latest
    depends_on:
    - s3
    entrypoint: >
      /bin/sh -c "
        mc config host add myminio http://s3:9000 minioadmin minioadmin;
        mc mb myminio/logs;
        exit 0;
      "

  enterprise-opa:
    image: ghcr.io/styrainc/enterprise-opa:latest
    ports:
    - "8181:8181"
    command:
    - "run"
    - "--server"
    - "--addr=0.0.0.0:8181"
    - "--log-level=debug"
    - "--config-file=/data/enterprise-opa.yml"
    environment:
      STYRA_LOAD_LICENSE_KEY: ${STYRA_LOAD_LICENSE_KEY}
    volumes:
    - "./enterprise-opa.yml:/data/enterprise-opa.yml"
    depends_on:
    - bucket

