---
apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-opa
---
apiVersion: v1
kind: Secret
metadata:
  name: styra-enterprise-opa-license
  namespace: enterprise-opa
type: Opaque
stringData:
  license: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: styra-enterprise-opa-config
  namespace: enterprise-opa
data:
  config.yaml: |
    decision_logs:
      console: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enterprise-opa
  namespace: enterprise-opa
  name: enterprise-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-opa
  template:
    metadata:
      labels:
        app: enterprise-opa
      name: enterprise-opa
    spec:
      containers:
      - name: enterprise-opa
        image: ghcr.io/styrainc/enterprise-opa:latest
        args:
        - "run"
        - "--server"
        - "--addr=0.0.0.0:8181"
        - "--config-file=/etc/config/config.yaml"
        env:
        - name: STYRA_ENTERPRISE_OPA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: styra-enterprise-opa-license
              key: license
        volumeMounts:
        - name: config
          mountPath: /etc/config
        readinessProbe:
          httpGet:
            path: /health
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: styra-enterprise-opa-config
          items:
          - key: "config.yaml"
            path: "config.yaml"
---
kind: Service
apiVersion: v1
metadata:
  name: enterprise-opa
  namespace: enterprise-opa
spec:
  selector:
    app: enterprise-opa
  ports:
  - port: 8181
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-opa
  namespace: enterprise-opa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /enterprise-opa(/|$)(.*)
        backend:
          service:
            name: enterprise-opa
            port:
              number: 8181
